name: web_socket_client
description: A simple WebSocket client for Dart which includes automatic reconnection logic.
repository: https://github.com/felangel/web_socket_client
version: 0.1.3
topics: [web-socket, web-socket-client]

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  web: ^0.5.0
  web_socket_channel: ">=2.4.5 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
